### ISSUE TITLE
Unable to find caughtBattleMonActor in handleCaptureInBattle

### ISSUE THREAD

**Issue by tmetcalfe89** [timinc-cobble/cobblemon-capture-xp-1.4-forge#7]
```
[03:28:20] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at us.timinc.mc.cobblemon.capturexp.CaptureXP.handleCaptureInBattle(CaptureXP.kt:32) ~[cobblemon-capturexp-1.3-fabric-1.0.3.jar:?]
	at us.timinc.mc.cobblemon.capturexp.CaptureXP.access$handleCaptureInBattle(CaptureXP.kt:15) ~[cobblemon-capturexp-1.3-fabric-1.0.3.jar:?]
	at us.timinc.mc.cobblemon.capturexp.CaptureXP$onInitialize$2.invoke(CaptureXP.kt:26) ~[cobblemon-capturexp-1.3-fabric-1.0.3.jar:?]
	at us.timinc.mc.cobblemon.capturexp.CaptureXP$onInitialize$2.invoke(CaptureXP.kt:25) ~[cobblemon-capturexp-1.3-fabric-1.0.3.jar:?]
	at com.cobblemon.mod.common.api.reactive.ObservableSubscription.handle(ObservableSubscription.java:17) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.api.reactive.SimpleObservable.emit(SimpleObservable.java:39) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.entity.pokeball.EmptyPokeBallEntity$shakeBall$1.invoke(EmptyPokeBallEntity.java:429) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.entity.pokeball.EmptyPokeBallEntity$shakeBall$1.invoke(EmptyPokeBallEntity.java:313) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.util.DistributionUtilsKt.runOnServer$lambda-3(DistributionUtilsKt.java:44) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[server-intermediary.jar:?]
	at com.cobblemon.mod.common.util.DistributionUtilsKt.runOnServer(DistributionUtilsKt.java:44) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.api.scheduling.SchedulingFunctionsKt$after$1.invoke(SchedulingFunctionsKt.java:16) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.api.scheduling.SchedulingFunctionsKt$after$1.invoke(SchedulingFunctionsKt.java:14) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.api.scheduling.ScheduledTask.update(ScheduledTask.java:66) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.api.scheduling.ScheduledTaskTracker.update(ScheduledTaskTracker.java:20) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.Cobblemon$initialize$3$1.invoke(Cobblemon.java:263) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.Cobblemon$initialize$3$1.invoke(Cobblemon.java:263) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.api.reactive.ObservableSubscription.handle(ObservableSubscription.java:17) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.api.reactive.SimpleObservable.emit(SimpleObservable.java:39) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at com.cobblemon.mod.common.util.EventExtensionsKt$asTickObservable$1.invoke$lambda-0(EventExtensionsKt.java:29) ~[Cobblemon-fabric-1.3.2+1.19.2.jar:?]
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732) ~[?:?]
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-6.5.85-fabric.jar:?]
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62) ~[architectury-6.5.85-fabric.jar:?]
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89) ~[guava-31.0.1-jre.jar:?]
	at jdk.proxy2.$Proxy131.tick(Unknown Source) ~[?:?]
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerCommon$13(EventHandlerImpl.java:71) ~[architectury-6.5.85-fabric.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62) ~[fabric-lifecycle-events-v1-2.2.4+1b46dc7890-cde405b3e4280340.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bja002$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:6321) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```
![image](https://github.com/timinc-cobble/cobblemon-capture-xp-1.4-fabric/assets/82600217/c141e056-fef9-40cc-bcd7-bfdb8d8da2d0)

**Comment by tmetcalfe89** [comment]
fixed by #8
